//LOGIN
export const ADD_LOGIN = "ADD_LOGIN";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const REMOVE_LOGIN = "REMOVE_LOGIN";

// ContainerSize actionTypes

export const CONTAINER_SIZE_GET_DATA = "CONTAINER_SIZE_GET_DATA";
export const CONTAINER_SIZE_SET_DATA = "CONTAINER_SIZE_SET_DATA";
export const CONTAINER_SIZE_FAIL_DATA = "CONTAINER_SIZE_FAIL_DATA";
export const DELETE_CONTAINER_SIZE_FAIL = "DELETE_CONTAINER_SIZE_FAIL";
export const POST_CONTAINER_SIZE_DATA = "POST_CONTAINER_SIZE_DATA";
export const POST_CONTAINER_SIZE_DATA_START = "POST_CONTAINER_SIZE_DATA_START";
export const POST_CONTAINER_SIZE_DATA_FAIL = "POST_CONTAINER_SIZE_DATA_FAIL";
export const POST_CONTAINER_SIZE_DATA_SUCCESS =
  "POST_CONTAINER_SIZE_DATA_SUCCESS";
export const EDIT_CONTAINER_SIZE_ROW_START = "EDIT_CONTAINER_SIZE_ROW_START";

export const FAIL_EDIT_CONTAINER_SIZE = "FAIL_EDIT_CONTAINER_SIZE";
export const CURRENT_USER_EDIT_CONTAINER_SIZE =
  "CURRENT_USER_EDIT_CONTAINER_SIZE";
export const UPDATE_CONTAINER_SIZE_DATA_START =
  "UPDATE_CONTAINER_SIZE_DATA_START";
export const UPDATE_CONTAINER_SIZE_DATA_FAIL =
  "UPDATE_CONTAINER_SIZE_DATA_FAIL";
export const UPDATE_CONTAINER_SIZE_DATA_SUCCESS =
  "UPDATE_CONTAINER_SIZE_DATA_SUCCESS";
export const CONTAINER_SIZE_LOADING = "CONTAINER_SIZE_LOADING";
export const CONTAINER_SIZE_POST_LOADING = "CONTAINER_SIZE_POST_LOADING";
export const CONTAINER_SIZE_UPDATE_LOADING = "CONTAINER_SIZE_UPDATE_LOADING";

// port of loading actionTypes

export const PORT_LOADING_GET_DATA = "PORT_LOADING_GET_DATA";
export const PORT_LOADING_SET_DATA = "PORT_LOADING_SET_DATA";
export const PORT_LOADING_FAIL_DATA = "PORT_LOADING_FAIL_DATA";
export const DELETE_PORT_LOADING_FAIL = "DELETE_PORT_LOADING_FAIL";
export const POST_PORT_LOADING_DATA = "POST_PORT_LOADING_DATA";
export const POST_PORT_LOADING_DATA_START = "POST_PORT_LOADING_DATA_START";
export const POST_PORT_LOADING_DATA_FAIL = "POST_PORT_LOADING_DATA_FAIL";
export const POST_PORT_LOADING_DATA_SUCCESS = "POST_PORT_LOADING_DATA_SUCCESS";
export const EDIT_PORT_LOADING_ROW_START = "EDIT_PORT_LOADING_ROW_START";

export const FAIL_EDIT_PORT_LOADING = "FAIL_EDIT_PORT_LOADING";
export const CURRENT_USER_EDIT_PORT_LOADING = "CURRENT_USER_EDIT_PORT_LOADING";
export const UPDATE_PORT_LOADING_DATA_START = "UPDATE_PORT_LOADING_DATA_START";
export const UPDATE_PORT_LOADING_DATA_FAIL = "UPDATE_PORT_LOADING_DATA_FAIL";
export const UPDATE_PORT_LOADING_DATA_SUCCESS =
  "UPDATE_PORT_LOADING_DATA_SUCCESS";
export const PORT_LOADING_LOADING = "PORT_LOADING_LOADING";
export const PORT_LOADING_POST_LOADING = "PORT_LOADING_POST_LOADING";
export const PORT_LOADING_UPDATE_LOADING = "PORT_LOADING_UPDATE_LOADING";

// port of discharge actionTypes

export const PORT_DISCHARGE_GET_DATA = "PORT_DISCHARGE_GET_DATA";
export const PORT_DISCHARGE_SET_DATA = "PORT_DISCHARGE_SET_DATA";
export const PORT_DISCHARGE_FAIL_DATA = "PORT_DISCHARGE_FAIL_DATA";
export const DELETE_PORT_DISCHARGE_FAIL = "DELETE_PORT_DISCHARGE_FAIL";
export const POST_PORT_DISCHARGE_DATA = "POST_PORT_DISCHARGE_DATA";
export const POST_PORT_DISCHARGE_DATA_START = "POST_PORT_DISCHARGE_DATA_START";
export const POST_PORT_DISCHARGE_DATA_FAIL = "POST_PORT_DISCHARGE_DATA_FAIL";
export const POST_PORT_DISCHARGE_DATA_SUCCESS =
  "POST_PORT_DISCHARGE_DATA_SUCCESS";
export const EDIT_PORT_DISCHARGE_ROW_START = "EDIT_PORT_DISCHARGE_ROW_START";

export const FAIL_EDIT_PORT_DISCHARGE = "FAIL_EDIT_PORT_DISCHARGE";
export const CURRENT_USER_EDIT_PORT_DISCHARGE =
  "CURRENT_USER_EDIT_PORT_DISCHARGE";
export const UPDATE_PORT_DISCHARGE_DATA_START =
  "UPDATE_PORT_DISCHARGE_DATA_START";
export const UPDATE_PORT_DISCHARGE_DATA_FAIL =
  "UPDATE_PORT_DISCHARGE_DATA_FAIL";
export const UPDATE_PORT_DISCHARGE_DATA_SUCCESS =
  "UPDATE_PORT_DISCHARGE_DATA_SUCCESS";
export const PORT_DISCHARGE_LOADING = "PORT_DISCHARGE_LOADING";
export const PORT_DISCHARGE_POST_LOADING = "PORT_DISCHARGE_POST_LOADING";
export const PORT_DISCHARGE_UPDATE_LOADING = "PORT_DISCHARGE_UPDATE_LOADING";

// port of Delivery actionTypes

export const PORT_DELIVERY_GET_DATA = "PORT_DELIVERY_GET_DATA";
export const PORT_DELIVERY_SET_DATA = "PORT_DELIVERY_SET_DATA";
export const PORT_DELIVERY_FAIL_DATA = "PORT_DELIVERY_FAIL_DATA";
export const DELETE_PORT_DELIVERY_FAIL = "DELETE_PORT_DELIVERY_FAIL";
export const POST_PORT_DELIVERY_DATA = "POST_PORT_DELIVERY_DATA";
export const POST_PORT_DELIVERY_DATA_START = "POST_PORT_DELIVERY_DATA_START";
export const POST_PORT_DELIVERY_DATA_FAIL = "POST_PORT_DELIVERY_DATA_FAIL";
export const POST_PORT_DELIVERY_DATA_SUCCESS =
  "POST_PORT_DELIVERY_DATA_SUCCESS";
export const EDIT_PORT_DELIVERY_ROW_START = "EDIT_PORT_DELIVERY_ROW_START";

export const FAIL_EDIT_PORT_DELIVERY = "FAIL_EDIT_PORT_DELIVERY";
export const CURRENT_USER_EDIT_PORT_DELIVERY =
  "CURRENT_USER_EDIT_PORT_DELIVERY";
export const UPDATE_PORT_DELIVERY_DATA_START =
  "UPDATE_PORT_DELIVERY_DATA_START";
export const UPDATE_PORT_DELIVERY_DATA_FAIL = "UPDATE_PORT_DELIVERY_DATA_FAIL";
export const UPDATE_PORT_DELIVERY_DATA_SUCCESS =
  "UPDATE_PORT_DELIVERY_DATA_SUCCESS";
export const PORT_DELIVERY_LOADING = "PORT_DELIVERY_LOADING";
export const PORT_DELIVERY_POST_LOADING = "PORT_DELIVERY_POST_LOADING";
export const PORT_DELIVERY_UPDATE_LOADING = "PORT_DELIVERY_UPDATE_LOADING";

// commission unit actionTypes

export const COMMISSION_UNIT_GET_DATA = "COMMISSION_UNIT_GET_DATA";
export const COMMISSION_UNIT_SET_DATA = "COMMISSION_UNIT_SET_DATA";
export const COMMISSION_UNIT_FAIL_DATA = "COMMISSION_UNIT_FAIL_DATA";
export const DELETE_COMMISSION_UNIT_FAIL = "DELETE_COMMISSION_UNIT_FAIL";
export const POST_COMMISSION_UNIT_DATA = "POST_COMMISSION_UNIT_DATA";
export const POST_COMMISSION_UNIT_DATA_START =
  "POST_COMMISSION_UNIT_DATA_START";
export const POST_COMMISSION_UNIT_DATA_FAIL = "POST_COMMISSION_UNIT_DATA_FAIL";
export const POST_COMMISSION_UNIT_DATA_SUCCESS =
  "POST_COMMISSION_UNIT_DATA_SUCCESS";
export const EDIT_COMMISSION_UNIT_ROW_START = "EDIT_COMMISSION_UNIT_ROW_START";

export const FAIL_EDIT_COMMISSION_UNIT = "FAIL_EDIT_COMMISSION_UNIT";
export const CURRENT_USER_EDIT_COMMISSION_UNIT =
  "CURRENT_USER_EDIT_COMMISSION_UNIT";
export const UPDATE_COMMISSION_UNIT_DATA_START =
  "UPDATE_COMMISSION_UNIT_DATA_START";
export const UPDATE_COMMISSION_UNIT_DATA_FAIL =
  "UPDATE_COMMISSION_UNIT_DATA_FAIL";
export const UPDATE_COMMISSION_UNIT_DATA_SUCCESS =
  "UPDATE_COMMISSION_UNIT_DATA_SUCCESS";
export const COMMISSION_UNIT_LOADING = "COMMISSION_UNIT_LOADING";
export const COMMISSION_UNIT_POST_LOADING = "COMMISSION_UNIT_POST_LOADING";
export const COMMISSION_UNIT_UPDATE_LOADING = "COMMISSION_UNIT_UPDATE_LOADING";

// quantity unit actionTypes

export const QUANTITY_UNIT_GET_DATA = "QUANTITY_UNIT_GET_DATA";
export const QUANTITY_UNIT_SET_DATA = "QUANTITY_UNIT_SET_DATA";
export const QUANTITY_UNIT_FAIL_DATA = "QUANTITY_UNIT_FAIL_DATA";
export const DELETE_QUANTITY_UNIT_FAIL = "DELETE_QUANTITY_UNIT_FAIL";
export const POST_QUANTITY_UNIT_DATA = "POST_QUANTITY_UNIT_DATA";
export const POST_QUANTITY_UNIT_DATA_START = "POST_QUANTITY_UNIT_DATA_START";
export const POST_QUANTITY_UNIT_DATA_FAIL = "POST_QUANTITY_UNIT_DATA_FAIL";
export const POST_QUANTITY_UNIT_DATA_SUCCESS =
  "POST_QUANTITY_UNIT_DATA_SUCCESS";
export const EDIT_QUANTITY_UNIT_ROW_START = "EDIT_QUANTITY_UNIT_ROW_START";

export const FAIL_EDIT_QUANTITY_UNIT = "FAIL_EDIT_QUANTITY_UNIT";
export const CURRENT_USER_EDIT_QUANTITY_UNIT =
  "CURRENT_USER_EDIT_QUANTITY_UNIT";
export const UPDATE_QUANTITY_UNIT_DATA_START =
  "UPDATE_QUANTITY_UNIT_DATA_START";
export const UPDATE_QUANTITY_UNIT_DATA_FAIL = "UPDATE_QUANTITY_UNIT_DATA_FAIL";
export const UPDATE_QUANTITY_UNIT_DATA_SUCCESS =
  "UPDATE_QUANTITY_UNIT_DATA_SUCCESS";
export const QUANTITY_UNIT_LOADING = "QUANTITY_UNIT_LOADING";
export const QUANTITY_UNIT_POST_LOADING = "QUANTITY_UNIT_POST_LOADING";
export const QUANTITY_UNIT_UPDATE_LOADING = "QUANTITY_UNIT_UPDATE_LOADING";

// price unit actionTypes

export const PRICE_UNIT_GET_DATA = "PRICE_UNIT_GET_DATA";
export const PRICE_UNIT_SET_DATA = "PRICE_UNIT_SET_DATA";
export const PRICE_UNIT_FAIL_DATA = "PRICE_UNIT_FAIL_DATA";
export const DELETE_PRICE_UNIT_FAIL = "DELETE_PRICE_UNIT_FAIL";
export const POST_PRICE_UNIT_DATA = "POST_PRICE_UNIT_DATA";
export const POST_PRICE_UNIT_DATA_START = "POST_PRICE_UNIT_DATA_START";
export const POST_PRICE_UNIT_DATA_FAIL = "POST_PRICE_UNIT_DATA_FAIL";
export const POST_PRICE_UNIT_DATA_SUCCESS = "POST_PRICE_UNIT_DATA_SUCCESS";
export const EDIT_PRICE_UNIT_ROW_START = "EDIT_PRICE_UNIT_ROW_START";

export const FAIL_EDIT_PRICE_UNIT = "FAIL_EDIT_PRICE_UNIT";
export const CURRENT_USER_EDIT_PRICE_UNIT = "CURRENT_USER_EDIT_PRICE_UNIT";
export const UPDATE_PRICE_UNIT_DATA_START = "UPDATE_PRICE_UNIT_DATA_START";
export const UPDATE_PRICE_UNIT_DATA_FAIL = "UPDATE_PRICE_UNIT_DATA_FAIL";
export const UPDATE_PRICE_UNIT_DATA_SUCCESS = "UPDATE_PRICE_UNIT_DATA_SUCCESS";
export const PRICE_UNIT_LOADING = "PRICE_UNIT_LOADING";
export const PRICE_UNIT_POST_LOADING = "PRICE_UNIT_POST_LOADING";
export const PRICE_UNIT_UPDATE_LOADING = "PRICE_UNIT_UPDATE_LOADING";

// weight unit actionTypes

export const WEIGHT_UNIT_GET_DATA = "WEIGHT_UNIT_GET_DATA";
export const WEIGHT_UNIT_SET_DATA = "WEIGHT_UNIT_SET_DATA";
export const WEIGHT_UNIT_FAIL_DATA = "WEIGHT_UNIT_FAIL_DATA";
export const DELETE_WEIGHT_UNIT_FAIL = "DELETE_WEIGHT_UNIT_FAIL";
export const POST_WEIGHT_UNIT_DATA = "POST_WEIGHT_UNIT_DATA";
export const POST_WEIGHT_UNIT_DATA_START = "POST_WEIGHT_UNIT_DATA_START";
export const POST_WEIGHT_UNIT_DATA_FAIL = "POST_WEIGHT_UNIT_DATA_FAIL";
export const POST_WEIGHT_UNIT_DATA_SUCCESS = "POST_WEIGHT_UNIT_DATA_SUCCESS";
export const EDIT_WEIGHT_UNIT_ROW_START = "EDIT_WEIGHT_UNIT_ROW_START";

export const FAIL_EDIT_WEIGHT_UNIT = "FAIL_EDIT_WEIGHT_UNIT";
export const CURRENT_USER_EDIT_WEIGHT_UNIT = "CURRENT_USER_EDIT_WEIGHT_UNIT";
export const UPDATE_WEIGHT_UNIT_DATA_START = "UPDATE_WEIGHT_UNIT_DATA_START";
export const UPDATE_WEIGHT_UNIT_DATA_FAIL = "UPDATE_WEIGHT_UNIT_DATA_FAIL";
export const UPDATE_WEIGHT_UNIT_DATA_SUCCESS =
  "UPDATE_WEIGHT_UNIT_DATA_SUCCESS";
export const WEIGHT_UNIT_LOADING = "WEIGHT_UNIT_LOADING";
export const WEIGHT_UNIT_POST_LOADING = "WEIGHT_UNIT_POST_LOADING";
export const WEIGHT_UNIT_UPDATE_LOADING = "WEIGHT_UNIT_UPDATE_LOADING";

// payment advance unit actionTypes

export const PAYMENT_ADVANCE_UNIT_GET_DATA = "PAYMENT_ADVANCE_UNIT_GET_DATA";
export const PAYMENT_ADVANCE_UNIT_SET_DATA = "PAYMENT_ADVANCE_UNIT_SET_DATA";
export const PAYMENT_ADVANCE_UNIT_FAIL_DATA = "PAYMENT_ADVANCE_UNIT_FAIL_DATA";
export const DELETE_PAYMENT_ADVANCE_UNIT_FAIL =
  "DELETE_PAYMENT_ADVANCE_UNIT_FAIL";
export const POST_PAYMENT_ADVANCE_UNIT_DATA = "POST_PAYMENT_ADVANCE_UNIT_DATA";
export const POST_PAYMENT_ADVANCE_UNIT_DATA_START =
  "POST_PAYMENT_ADVANCE_UNIT_DATA_START";
export const POST_PAYMENT_ADVANCE_UNIT_DATA_FAIL =
  "POST_PAYMENT_ADVANCE_UNIT_DATA_FAIL";
export const POST_PAYMENT_ADVANCE_UNIT_DATA_SUCCESS =
  "POST_PAYMENT_ADVANCE_UNIT_DATA_SUCCESS";
export const EDIT_PAYMENT_ADVANCE_UNIT_ROW_START =
  "EDIT_PAYMENT_ADVANCE_UNIT_ROW_START";

export const FAIL_EDIT_PAYMENT_ADVANCE_UNIT = "FAIL_EDIT_PAYMENT_ADVANCE_UNIT";
export const CURRENT_USER_EDIT_PAYMENT_ADVANCE_UNIT =
  "CURRENT_USER_EDIT_PAYMENT_ADVANCE_UNIT";
export const UPDATE_PAYMENT_ADVANCE_UNIT_DATA_START =
  "UPDATE_PAYMENT_ADVANCE_UNIT_DATA_START";
export const UPDATE_PAYMENT_ADVANCE_UNIT_DATA_FAIL =
  "UPDATE_PAYMENT_ADVANCE_UNIT_DATA_FAIL";
export const UPDATE_PAYMENT_ADVANCE_UNIT_DATA_SUCCESS =
  "UPDATE_PAYMENT_ADVANCE_UNIT_DATA_SUCCESS";
export const PAYMENT_ADVANCE_UNIT_LOADING = "PAYMENT_ADVANCE_UNIT_LOADING";
export const PAYMENT_ADVANCE_UNIT_POST_LOADING =
  "PAYMENT_ADVANCE_UNIT_POST_LOADING";
export const PAYMENT_ADVANCE_UNIT_UPDATE_LOADING =
  "PAYMENT_ADVANCE_UNIT_UPDATE_LOADING";

// payment pending unit actionTypes

export const PAYMENT_PENDING_UNIT_GET_DATA = "PAYMENT_PENDING_UNIT_GET_DATA";
export const PAYMENT_PENDING_UNIT_SET_DATA = "PAYMENT_PENDING_UNIT_SET_DATA";
export const PAYMENT_PENDING_UNIT_FAIL_DATA = "PAYMENT_PENDING_UNIT_FAIL_DATA";
export const DELETE_PAYMENT_PENDING_UNIT_FAIL =
  "DELETE_PAYMENT_PENDING_UNIT_FAIL";
export const POST_PAYMENT_PENDING_UNIT_DATA = "POST_PAYMENT_PENDING_UNIT_DATA";
export const POST_PAYMENT_PENDING_UNIT_DATA_START =
  "POST_PAYMENT_PENDING_UNIT_DATA_START";
export const POST_PAYMENT_PENDING_UNIT_DATA_FAIL =
  "POST_PAYMENT_PENDING_UNIT_DATA_FAIL";
export const POST_PAYMENT_PENDING_UNIT_DATA_SUCCESS =
  "POST_PAYMENT_PENDING_UNIT_DATA_SUCCESS";
export const EDIT_PAYMENT_PENDING_UNIT_ROW_START =
  "EDIT_PAYMENT_PENDING_UNIT_ROW_START";

export const FAIL_EDIT_PAYMENT_PENDING_UNIT = "FAIL_EDIT_PAYMENT_PENDING_UNIT";
export const CURRENT_USER_EDIT_PAYMENT_PENDING_UNIT =
  "CURRENT_USER_EDIT_PAYMENT_PENDING_UNIT";
export const UPDATE_PAYMENT_PENDING_UNIT_DATA_START =
  "UPDATE_PAYMENT_PENDING_UNIT_DATA_START";
export const UPDATE_PAYMENT_PENDING_UNIT_DATA_FAIL =
  "UPDATE_PAYMENT_PENDING_UNIT_DATA_FAIL";
export const UPDATE_PAYMENT_PENDING_UNIT_DATA_SUCCESS =
  "UPDATE_PAYMENT_PENDING_UNIT_DATA_SUCCESS";
export const PAYMENT_PENDING_UNIT_LOADING = "PAYMENT_PENDING_UNIT_LOADING";
export const PAYMENT_PENDING_UNIT_POST_LOADING =
  "PAYMENT_PENDING_UNIT_POST_LOADING";
export const PAYMENT_PENDING_UNIT_UPDATE_LOADING =
  "PAYMENT_PENDING_UNIT_UPDATE_LOADING";

// Commodity actionTypes

export const COMMODITY_GET_DATA = "COMMODITY_GET_DATA";
export const COMMODITY_SET_DATA = "COMMODITY_SET_DATA";
export const COMMODITY_FAIL_DATA = "COMMODITY_FAIL_DATA";
export const DELETE_COMMODITY_FAIL = "DELETE_COMMODITY_FAIL";
export const POST_COMMODITY_DATA = "POST_COMMODITY_DATA";
export const POST_COMMODITY_DATA_START = "POST_COMMODITY_DATA_START";
export const POST_COMMODITY_DATA_FAIL = "POST_COMMODITY_DATA_FAIL";
export const POST_COMMODITY_DATA_SUCCESS = "POST_COMMODITY_DATA_SUCCESS";
export const EDIT_COMMODITY_ROW_START = "EDIT_COMMODITY_ROW_START";

export const FAIL_EDIT_COMMODITY = "FAIL_EDIT_COMMODITY";
export const CURRENT_USER_EDIT_COMMODITY = "CURRENT_USER_EDIT_COMMODITY";
export const UPDATE_COMMODITY_DATA_START = "UPDATE_COMMODITY_DATA_START";
export const UPDATE_COMMODITY_DATA_FAIL = "UPDATE_COMMODITY_DATA_FAIL";
export const UPDATE_COMMODITY_DATA_SUCCESS = "UPDATE_COMMODITY_DATA_SUCCESS";
export const COMMODITY_LOADING = "COMMODITY_LOADING";
export const COMMODITY_POST_LOADING = "COMMODITY_POST_LOADING";
export const COMMODITY_UPDATE_LOADING = "COMMODITY_UPDATE_LOADING";

// Commodity Analysis actionTypes

export const COMMODITY_ANALYSIS_GET_DATA = "COMMODITY_ANALYSIS_GET_DATA";
export const COMMODITY_ANALYSIS_SET_DATA = "COMMODITY_ANALYSIS_SET_DATA";
export const COMMODITY_ANALYSIS_FAIL_DATA = "COMMODITY_ANALYSIS_FAIL_DATA";
export const DELETE_COMMODITY_ANALYSIS_FAIL = "DELETE_COMMODITY_ANALYSIS_FAIL";
export const POST_COMMODITY_ANALYSIS_DATA = "POST_COMMODITY_ANALYSIS_DATA";
export const POST_COMMODITY_ANALYSIS_DATA_START =
  "POST_COMMODITY_ANALYSIS_DATA_START";
export const POST_COMMODITY_ANALYSIS_DATA_FAIL =
  "POST_COMMODITY_ANALYSIS_DATA_FAIL";
export const POST_COMMODITY_ANALYSIS_DATA_SUCCESS =
  "POST_COMMODITY_ANALYSIS_DATA_SUCCESS";
export const EDIT_COMMODITY_ANALYSIS_ROW_START =
  "EDIT_COMMODITY_ANALYSIS_ROW_START";

export const FAIL_EDIT_COMMODITY_ANALYSIS = "FAIL_EDIT_COMMODITY_ANALYSIS";
export const CURRENT_USER_EDIT_COMMODITY_ANALYSIS =
  "CURRENT_USER_EDIT_COMMODITY_ANALYSIS";
export const UPDATE_COMMODITY_ANALYSIS_DATA_START =
  "UPDATE_COMMODITY_ANALYSIS_DATA_START";
export const UPDATE_COMMODITY_ANALYSIS_DATA_FAIL =
  "UPDATE_COMMODITY_ANALYSIS_DATA_FAIL";
export const UPDATE_COMMODITY_ANALYSIS_DATA_SUCCESS =
  "UPDATE_COMMODITY_ANALYSIS_DATA_SUCCESS";
export const COMMODITY_ANALYSIS_LOADING = "COMMODITY_ANALYSIS_LOADING";
export const COMMODITY_ANALYSIS_POST_LOADING =
  "COMMODITY_ANALYSIS_POST_LOADING";
export const COMMODITY_ANALYSIS_UPDATE_LOADING =
  "COMMODITY_ANALYSIS_UPDATE_LOADING";

// suppiler actionTypes

export const SUPPILER_GET_DATA = "SUPPILER_GET_DATA";
export const SUPPILER_SET_DATA = "SUPPILER_SET_DATA";
export const SUPPILER_FAIL_DATA = "SUPPILER_FAIL_DATA";
export const DELETE_SUPPILER_FAIL = "DELETE_SUPPILER_FAIL";
export const POST_SUPPILER_DATA = "POST_SUPPILER_DATA";
export const POST_SUPPILER_DATA_START = "POST_SUPPILER_DATA_START";
export const POST_SUPPILER_DATA_FAIL = "POST_SUPPILER_DATA_FAIL";
export const POST_SUPPILER_DATA_SUCCESS = "POST_SUPPILER_DATA_SUCCESS";
export const EDIT_SUPPILER_ROW_START = "EDIT_SUPPILER_ROW_START";

export const FAIL_EDIT_SUPPILER = "FAIL_EDIT_SUPPILER";
export const CURRENT_USER_EDIT_SUPPILER = "CURRENT_USER_EDIT_SUPPILER";
export const UPDATE_SUPPILER_DATA_START = "UPDATE_SUPPILER_DATA_START";
export const UPDATE_SUPPILER_DATA_FAIL = "UPDATE_SUPPILER_DATA_FAIL";
export const UPDATE_SUPPILER_DATA_SUCCESS = "UPDATE_SUPPILER_DATA_SUCCESS";
export const SUPPILER_LOADING = "SUPPILER_LOADING";
export const SUPPILER_POST_LOADING = "SUPPILER_POST_LOADING";
export const SUPPILER_UPDATE_LOADING = "SUPPILER_UPDATE_LOADING";

// Country actionTypes

export const COUNTRY_GET_DATA = "COUNTRY_GET_DATA";
export const COUNTRY_SET_DATA = "COUNTRY_SET_DATA";
export const COUNTRY_FAIL_DATA = "COUNTRY_FAIL_DATA";
export const DELETE_COUNTRY_FAIL = "DELETE_COUNTRY_FAIL";
export const POST_COUNTRY_DATA = "POST_COUNTRY_DATA";
export const POST_COUNTRY_DATA_START = "POST_COUNTRY_DATA_START";
export const POST_COUNTRY_DATA_FAIL = "POST_COUNTRY_DATA_FAIL";
export const POST_COUNTRY_DATA_SUCCESS = "POST_COUNTRY_DATA_SUCCESS";
export const EDIT_COUNTRY_ROW_START = "EDIT_COUNTRY_ROW_START";

export const FAIL_EDIT_COUNTRY = "FAIL_EDIT_COUNTRY";
export const CURRENT_USER_EDIT_COUNTRY = "CURRENT_USER_EDIT_COUNTRY";
export const UPDATE_COUNTRY_DATA_START = "UPDATE_COUNTRY_DATA_START";
export const UPDATE_COUNTRY_DATA_FAIL = "UPDATE_COUNTRY_DATA_FAIL";
export const UPDATE_COUNTRY_DATA_SUCCESS = "UPDATE_COUNTRY_DATA_SUCCESS";
export const COUNTRY_LOADING = "COUNTRY_LOADING";
export const COUNTRY_POST_LOADING = "COUNTRY_POST_LOADING";
export const COUNTRY_UPDATE_LOADING = "COUNTRY_UPDATE_LOADING";

// State actionTypes

export const STATE_GET_DATA = "STATE_GET_DATA";
export const STATE_SET_DATA = "STATE_SET_DATA";
export const STATE_FAIL_DATA = "STATE_FAIL_DATA";
export const DELETE_STATE_FAIL = "DELETE_STATE_FAIL";
export const POST_STATE_DATA = "POST_STATE_DATA";
export const POST_STATE_DATA_START = "POST_STATE_DATA_START";
export const POST_STATE_DATA_FAIL = "POST_STATE_DATA_FAIL";
export const POST_STATE_DATA_SUCCESS = "POST_STATE_DATA_SUCCESS";
export const EDIT_STATE_ROW_START = "EDIT_STATE_ROW_START";

export const FAIL_EDIT_STATE = "FAIL_EDIT_STATE";
export const CURRENT_USER_EDIT_STATE = "CURRENT_USER_EDIT_STATE";
export const UPDATE_STATE_DATA_START = "UPDATE_STATE_DATA_START";
export const UPDATE_STATE_DATA_FAIL = "UPDATE_STATE_DATA_FAIL";
export const UPDATE_STATE_DATA_SUCCESS = "UPDATE_STATE_DATA_SUCCESS";
export const STATE_LOADING = "STATE_LOADING";
export const STATE_POST_LOADING = "STATE_POST_LOADING";
export const STATE_UPDATE_LOADING = "STATE_UPDATE_LOADING";

// City actionTypes

export const CITY_GET_DATA = "CITY_GET_DATA";
export const CITY_SET_DATA = "CITY_SET_DATA";
export const CITY_FAIL_DATA = "CITY_FAIL_DATA";
export const DELETE_CITY_FAIL = "DELETE_CITY_FAIL";
export const POST_CITY_DATA = "POST_CITY_DATA";
export const POST_CITY_DATA_START = "POST_CITY_DATA_START";
export const POST_CITY_DATA_FAIL = "POST_CITY_DATA_FAIL";
export const POST_CITY_DATA_SUCCESS = "POST_CITY_DATA_SUCCESS";
export const EDIT_CITY_ROW_START = "EDIT_CITY_ROW_START";

export const FAIL_EDIT_CITY = "FAIL_EDIT_CITY";
export const CURRENT_USER_EDIT_CITY = "CURRENT_USER_EDIT_CITY";
export const UPDATE_CITY_DATA_START = "UPDATE_CITY_DATA_START";
export const UPDATE_CITY_DATA_FAIL = "UPDATE_CITY_DATA_FAIL";
export const UPDATE_CITY_DATA_SUCCESS = "UPDATE_CITY_DATA_SUCCESS";
export const CITY_LOADING = "CITY_LOADING";
export const CITY_POST_LOADING = "CITY_POST_LOADING";
export const CITY_UPDATE_LOADING = "CITY_UPDATE_LOADING";

// Pucharse Order actionTypes

export const PURCHASE_ORDER_GET_DATA = "PURCHASE_ORDER_GET_DATA";
export const PURCHASE_ORDER_SET_DATA = "PURCHASE_ORDER_SET_DATA";
export const PURCHASE_ORDER_FAIL_DATA = "PURCHASE_ORDER_FAIL_DATA";
export const DELETE_PURCHASE_ORDER_FAIL = "DELETE_PURCHASE_ORDER_FAIL";
export const POST_PURCHASE_ORDER_DATA = "POST_PURCHASE_ORDER_DATA";
export const POST_PURCHASE_ORDER_DATA_START = "POST_PURCHASE_ORDER_DATA_START";
export const POST_PURCHASE_ORDER_DATA_FAIL = "POST_PURCHASE_ORDER_DATA_FAIL";
export const POST_PURCHASE_ORDER_DATA_SUCCESS =
  "POST_PURCHASE_ORDER_DATA_SUCCESS";
export const EDIT_PURCHASE_ORDER_ROW_START = "EDIT_PURCHASE_ORDER_ROW_START";

export const FAIL_EDIT_PURCHASE_ORDER = "FAIL_EDIT_PURCHASE_ORDER";
export const CURRENT_USER_EDIT_PURCHASE_ORDER =
  "CURRENT_USER_EDIT_PURCHASE_ORDER";
export const UPDATE_PURCHASE_ORDER_DATA_START =
  "UPDATE_PURCHASE_ORDER_DATA_START";
export const UPDATE_PURCHASE_ORDER_DATA_FAIL =
  "UPDATE_PURCHASE_ORDER_DATA_FAIL";
export const UPDATE_PURCHASE_ORDER_DATA_SUCCESS =
  "UPDATE_PURCHASE_ORDER_DATA_SUCCESS";
export const PURCHASE_ORDER_LOADING = "PURCHASE_ORDER_LOADING";
export const PURCHASE_ORDER_POST_LOADING = "PURCHASE_ORDER_POST_LOADING";
export const PURCHASE_ORDER_UPDATE_LOADING = "PURCHASE_ORDER_UPDATE_LOADING";

// Email Ref actionTypes

export const EMAIL_REF_GET_DATA = "EMAIL_REF_GET_DATA";
export const EMAIL_REF_SET_DATA = "EMAIL_REF_SET_DATA";
export const EMAIL_REF_FAIL_DATA = "EMAIL_REF_FAIL_DATA";
export const DELETE_EMAIL_REF_FAIL = "DELETE_EMAIL_REF_FAIL";
export const POST_EMAIL_REF_DATA = "POST_EMAIL_REF_DATA";
export const POST_EMAIL_REF_DATA_START = "POST_EMAIL_REF_DATA_START";
export const POST_EMAIL_REF_DATA_FAIL = "POST_EMAIL_REF_DATA_FAIL";
export const POST_EMAIL_REF_DATA_SUCCESS = "POST_EMAIL_REF_DATA_SUCCESS";
export const EDIT_EMAIL_REF_ROW_START = "EDIT_EMAIL_REF_ROW_START";

export const FAIL_EDIT_EMAIL_REF = "FAIL_EDIT_EMAIL_REF";
export const CURRENT_USER_EDIT_EMAIL_REF = "CURRENT_USER_EDIT_EMAIL_REF";
export const UPDATE_EMAIL_REF_DATA_START = "UPDATE_EMAIL_REF_DATA_START";
export const UPDATE_EMAIL_REF_DATA_FAIL = "UPDATE_EMAIL_REF_DATA_FAIL";
export const UPDATE_EMAIL_REF_DATA_SUCCESS = "UPDATE_EMAIL_REF_DATA_SUCCESS";
export const EMAIL_REF_LOADING = "EMAIL_REF_LOADING";
export const EMAIL_REF_POST_LOADING = "EMAIL_REF_POST_LOADING";
export const EMAIL_REF_UPDATE_LOADING = "EMAIL_REF_UPDATE_LOADING";

// Purchase sales Indent actionTypes

export const PURCHASE_SALES_INDENT_GET_DATA = "PURCHASE_SALES_INDENT_GET_DATA";
export const PURCHASE_SALES_INDENT_SET_DATA = "PURCHASE_SALES_INDENT_SET_DATA";
export const PURCHASE_SALES_INDENT_FAIL_DATA =
  "PURCHASE_SALES_INDENT_FAIL_DATA";
export const DELETE_PURCHASE_SALES_INDENT_FAIL =
  "DELETE_PURCHASE_SALES_INDENT_FAIL";
export const POST_PURCHASE_SALES_INDENT_DATA =
  "POST_PURCHASE_SALES_INDENT_DATA";
export const POST_PURCHASE_SALES_INDENT_DATA_START =
  "POST_PURCHASE_SALES_INDENT_DATA_START";
export const POST_PURCHASE_SALES_INDENT_DATA_FAIL =
  "POST_PURCHASE_SALES_INDENT_DATA_FAIL";
export const POST_PURCHASE_SALES_INDENT_DATA_SUCCESS =
  "POST_PURCHASE_SALES_INDENT_DATA_SUCCESS";
export const EDIT_PURCHASE_SALES_INDENT_ROW_START =
  "EDIT_PURCHASE_SALES_INDENT_ROW_START";

export const FAIL_EDIT_PURCHASE_SALES_INDENT =
  "FAIL_EDIT_PURCHASE_SALES_INDENT";
export const CURRENT_USER_EDIT_PURCHASE_SALES_INDENT =
  "CURRENT_USER_EDIT_PURCHASE_SALES_INDENT";
export const UPDATE_PURCHASE_SALES_INDENT_DATA_START =
  "UPDATE_PURCHASE_SALES_INDENT_DATA_START";
export const UPDATE_PURCHASE_SALES_INDENT_DATA_FAIL =
  "UPDATE_PURCHASE_SALES_INDENT_DATA_FAIL";
export const UPDATE_PURCHASE_SALES_INDENT_DATA_SUCCESS =
  "UPDATE_PURCHASE_SALES_INDENT_DATA_SUCCESS";
export const PURCHASE_SALES_INDENT_LOADING = "PURCHASE_SALES_INDENT_LOADING";
export const PURCHASE_SALES_INDENT_POST_LOADING =
  "PURCHASE_SALES_INDENT_POST_LOADING";
export const PURCHASE_SALES_INDENT_UPDATE_LOADING =
  "PURCHASE_SALES_INDENT_UPDATE_LOADING";

// Lme Update actionTypes

export const LME_UPDATE_GET_DATA = "LME_UPDATE_GET_DATA";
export const LME_UPDATE_SET_DATA = "LME_UPDATE_SET_DATA";
export const LME_UPDATE_FAIL_DATA = "LME_UPDATE_FAIL_DATA";
export const DELETE_LME_UPDATE_FAIL = "DELETE_LME_UPDATE_FAIL";
export const POST_LME_UPDATE_DATA = "POST_LME_UPDATE_DATA";
export const POST_LME_UPDATE_DATA_START = "POST_LME_UPDATE_DATA_START";
export const POST_LME_UPDATE_DATA_FAIL = "POST_LME_UPDATE_DATA_FAIL";
export const POST_LME_UPDATE_DATA_SUCCESS = "POST_LME_UPDATE_DATA_SUCCESS";
export const EDIT_LME_UPDATE_ROW_START = "EDIT_LME_UPDATE_ROW_START";

export const FAIL_EDIT_LME_UPDATE = "FAIL_EDIT_LME_UPDATE";
export const CURRENT_USER_EDIT_LME_UPDATE = "CURRENT_USER_EDIT_LME_UPDATE";
export const UPDATE_LME_UPDATE_DATA_START = "UPDATE_LME_UPDATE_DATA_START";
export const UPDATE_LME_UPDATE_DATA_FAIL = "UPDATE_LME_UPDATE_DATA_FAIL";
export const UPDATE_LME_UPDATE_DATA_SUCCESS = "UPDATE_LME_UPDATE_DATA_SUCCESS";
export const LME_UPDATE_LOADING = "LME_UPDATE_LOADING";
export const LME_UPDATE_POST_LOADING = "LME_UPDATE_POST_LOADING";
export const LME_UPDATE_UPDATE_LOADING = "LME_UPDATE_UPDATE_LOADING";

// Advance Detail actionTypes

export const ADVANCE_DETAIL_GET_DATA = "ADVANCE_DETAIL_GET_DATA";
export const ADVANCE_DETAIL_SET_DATA = "ADVANCE_DETAIL_SET_DATA";
export const ADVANCE_DETAIL_FAIL_DATA = "ADVANCE_DETAIL_FAIL_DATA";
export const DELETE_ADVANCE_DETAIL_FAIL = "DELETE_ADVANCE_DETAIL_FAIL";
export const POST_ADVANCE_DETAIL_DATA = "POST_ADVANCE_DETAIL_DATA";
export const POST_ADVANCE_DETAIL_DATA_START = "POST_ADVANCE_DETAIL_DATA_START";
export const POST_ADVANCE_DETAIL_DATA_FAIL = "POST_ADVANCE_DETAIL_DATA_FAIL";
export const POST_ADVANCE_DETAIL_DATA_SUCCESS =
  "POST_ADVANCE_DETAIL_DATA_SUCCESS";
export const EDIT_ADVANCE_DETAIL_ROW_START = "EDIT_ADVANCE_DETAIL_ROW_START";

export const FAIL_EDIT_ADVANCE_DETAIL = "FAIL_EDIT_ADVANCE_DETAIL";
export const CURRENT_USER_EDIT_ADVANCE_DETAIL =
  "CURRENT_USER_EDIT_ADVANCE_DETAIL";
export const UPDATE_ADVANCE_DETAIL_DATA_START =
  "UPDATE_ADVANCE_DETAIL_DATA_START";
export const UPDATE_ADVANCE_DETAIL_DATA_FAIL =
  "UPDATE_ADVANCE_DETAIL_DATA_FAIL";
export const UPDATE_ADVANCE_DETAIL_DATA_SUCCESS =
  "UPDATE_ADVANCE_DETAIL_DATA_SUCCESS";
export const ADVANCE_DETAIL_LOADING = "ADVANCE_DETAIL_LOADING";
export const ADVANCE_DETAIL_POST_LOADING = "ADVANCE_DETAIL_POST_LOADING";
export const ADVANCE_DETAIL_UPDATE_LOADING = "ADVANCE_DETAIL_UPDATE_LOADING";

// Loading Detail actionTypes

export const LOADING_DETAIL_GET_DATA = "LOADING_DETAIL_GET_DATA";
export const LOADING_DETAIL_SET_DATA = "LOADING_DETAIL_SET_DATA";
export const LOADING_DETAIL_FAIL_DATA = "LOADING_DETAIL_FAIL_DATA";
export const DELETE_LOADING_DETAIL_FAIL = "DELETE_LOADING_DETAIL_FAIL";
export const POST_LOADING_DETAIL_DATA = "POST_LOADING_DETAIL_DATA";
export const POST_LOADING_DETAIL_DATA_START = "POST_LOADING_DETAIL_DATA_START";
export const POST_LOADING_DETAIL_DATA_FAIL = "POST_LOADING_DETAIL_DATA_FAIL";
export const POST_LOADING_DETAIL_DATA_SUCCESS =
  "POST_LOADING_DETAIL_DATA_SUCCESS";
export const EDIT_LOADING_DETAIL_ROW_START = "EDIT_LOADING_DETAIL_ROW_START";

export const FAIL_EDIT_LOADING_DETAIL = "FAIL_EDIT_LOADING_DETAIL";
export const CURRENT_USER_EDIT_LOADING_DETAIL =
  "CURRENT_USER_EDIT_LOADING_DETAIL";
export const UPDATE_LOADING_DETAIL_DATA_START =
  "UPDATE_LOADING_DETAIL_DATA_START";
export const UPDATE_LOADING_DETAIL_DATA_FAIL =
  "UPDATE_LOADING_DETAIL_DATA_FAIL";
export const UPDATE_LOADING_DETAIL_DATA_SUCCESS =
  "UPDATE_LOADING_DETAIL_DATA_SUCCESS";
export const LOADING_DETAIL_LOADING = "LOADING_DETAIL_LOADING";
export const LOADING_DETAIL_POST_LOADING = "LOADING_DETAIL_POST_LOADING";
export const LOADING_DETAIL_UPDATE_LOADING = "LOADING_DETAIL_UPDATE_LOADING";

// File Upload actionTypes

export const FILE_UPLOAD_GET_DATA = "FILE_UPLOAD_GET_DATA";
export const FILE_UPLOAD_SET_DATA = "FILE_UPLOAD_SET_DATA";
export const FILE_UPLOAD_FAIL_DATA = "FILE_UPLOAD_FAIL_DATA";
export const DELETE_FILE_UPLOAD_FAIL = "DELETE_FILE_UPLOAD_FAIL";
export const POST_FILE_UPLOAD_DATA = "POST_FILE_UPLOAD_DATA";
export const POST_FILE_UPLOAD_DATA_START = "POST_FILE_UPLOAD_DATA_START";
export const POST_FILE_UPLOAD_DATA_FAIL = "POST_FILE_UPLOAD_DATA_FAIL";
export const POST_FILE_UPLOAD_DATA_SUCCESS = "POST_FILE_UPLOAD_DATA_SUCCESS";
export const EDIT_FILE_UPLOAD_ROW_START = "EDIT_FILE_UPLOAD_ROW_START";

export const FAIL_EDIT_FILE_UPLOAD = "FAIL_EDIT_FILE_UPLOAD";
export const CURRENT_USER_EDIT_FILE_UPLOAD = "CURRENT_USER_EDIT_FILE_UPLOAD";
export const UPDATE_FILE_UPLOAD_DATA_START = "UPDATE_FILE_UPLOAD_DATA_START";
export const UPDATE_FILE_UPLOAD_DATA_FAIL = "UPDATE_FILE_UPLOAD_DATA_FAIL";
export const UPDATE_FILE_UPLOAD_DATA_SUCCESS =
  "UPDATE_FILE_UPLOAD_DATA_SUCCESS";
export const FILE_UPLOAD_LOADING = "FILE_UPLOAD_LOADING";
export const FILE_UPLOAD_POST_LOADING = "FILE_UPLOAD_POST_LOADING";
export const FILE_UPLOAD_UPDATE_LOADING = "FILE_UPLOAD_UPDATE_LOADING";

// User history actionTypes

export const USER_HISTORY_GET_DATA = "USER_HISTORY_GET_DATA";
export const USER_HISTORY_SET_DATA = "USER_HISTORY_SET_DATA";
export const USER_HISTORY_FAIL_DATA = "USER_HISTORY_FAIL_DATA";
export const DELETE_USER_HISTORY_FAIL = "DELETE_USER_HISTORY_FAIL";
export const POST_USER_HISTORY_DATA = "POST_USER_HISTORY_DATA";
export const POST_USER_HISTORY_DATA_START = "POST_USER_HISTORY_DATA_START";
export const POST_USER_HISTORY_DATA_FAIL = "POST_USER_HISTORY_DATA_FAIL";
export const POST_USER_HISTORY_DATA_SUCCESS = "POST_USER_HISTORY_DATA_SUCCESS";
export const EDIT_USER_HISTORY_ROW_START = "EDIT_USER_HISTORY_ROW_START";

export const FAIL_EDIT_USER_HISTORY = "FAIL_EDIT_USER_HISTORY";
export const CURRENT_USER_EDIT_USER_HISTORY = "CURRENT_USER_EDIT_USER_HISTORY";
export const UPDATE_USER_HISTORY_DATA_START = "UPDATE_USER_HISTORY_DATA_START";
export const UPDATE_USER_HISTORY_DATA_FAIL = "UPDATE_USER_HISTORY_DATA_FAIL";
export const UPDATE_USER_HISTORY_DATA_SUCCESS =
  "UPDATE_USER_HISTORY_DATA_SUCCESS";
export const USER_HISTORY_LOADING = "USER_HISTORY_LOADING";
export const USER_HISTORY_POST_LOADING = "USER_HISTORY_POST_LOADING";
export const USER_HISTORY_UPDATE_LOADING = "USER_HISTORY_UPDATE_LOADING";

// Count actionTypes

export const COUNT_GET_DATA = "COUNT_GET_DATA";
export const COUNT_SET_DATA = "COUNT_SET_DATA";
export const COUNT_FAIL_DATA = "COUNT_FAIL_DATA";
export const DELETE_COUNT_FAIL = "DELETE_COUNT_FAIL";
export const POST_COUNT_DATA = "POST_COUNT_DATA";
export const POST_COUNT_DATA_START = "POST_COUNT_DATA_START";
export const POST_COUNT_DATA_FAIL = "POST_COUNT_DATA_FAIL";
export const POST_COUNT_DATA_SUCCESS = "POST_COUNT_DATA_SUCCESS";
export const EDIT_COUNT_ROW_START = "EDIT_COUNT_ROW_START";

export const FAIL_EDIT_COUNT = "FAIL_EDIT_COUNT";
export const CURRENT_USER_EDIT_COUNT = "CURRENT_USER_EDIT_COUNT";
export const UPDATE_COUNT_DATA_START = "UPDATE_COUNT_DATA_START";
export const UPDATE_COUNT_DATA_FAIL = "UPDATE_COUNT_DATA_FAIL";
export const UPDATE_COUNT_DATA_SUCCESS = "UPDATE_COUNT_DATA_SUCCESS";
export const COUNT_LOADING = "COUNT_LOADING";
export const COUNT_POST_LOADING = "COUNT_POST_LOADING";
export const COUNT_UPDATE_LOADING = "COUNT_UPDATE_LOADING";

// BPO GRAPH actionTypes

export const BPO_GRAPH_GET_DATA = "BPO_GRAPH_GET_DATA";
export const BPO_GRAPH_SET_DATA = "BPO_GRAPH_SET_DATA";
export const BPO_GRAPH_FAIL_DATA = "BPO_GRAPH_FAIL_DATA";
export const DELETE_BPO_GRAPH_FAIL = "DELETE_BPO_GRAPH_FAIL";
export const POST_BPO_GRAPH_DATA = "POST_BPO_GRAPH_DATA";
export const POST_BPO_GRAPH_DATA_START = "POST_BPO_GRAPH_DATA_START";
export const POST_BPO_GRAPH_DATA_FAIL = "POST_BPO_GRAPH_DATA_FAIL";
export const POST_BPO_GRAPH_DATA_SUCCESS = "POST_BPO_GRAPH_DATA_SUCCESS";
export const EDIT_BPO_GRAPH_ROW_START = "EDIT_BPO_GRAPH_ROW_START";

export const FAIL_EDIT_BPO_GRAPH = "FAIL_EDIT_BPO_GRAPH";
export const CURRENT_USER_EDIT_BPO_GRAPH = "CURRENT_USER_EDIT_BPO_GRAPH";
export const UPDATE_BPO_GRAPH_DATA_START = "UPDATE_BPO_GRAPH_DATA_START";
export const UPDATE_BPO_GRAPH_DATA_FAIL = "UPDATE_BPO_GRAPH_DATA_FAIL";
export const UPDATE_BPO_GRAPH_DATA_SUCCESS = "UPDATE_BPO_GRAPH_DATA_SUCCESS";
export const BPO_GRAPH_LOADING = "BPO_GRAPH_LOADING";
export const BPO_GRAPH_POST_LOADING = "BPO_GRAPH_POST_LOADING";
export const BPO_GRAPH_UPDATE_LOADING = "BPO_GRAPH_UPDATE_LOADING";

// GBQ GRAPH actionTypes

export const GBQ_GRAPH_GET_DATA = "GBQ_GRAPH_GET_DATA";
export const GBQ_GRAPH_SET_DATA = "GBQ_GRAPH_SET_DATA";
export const GBQ_GRAPH_FAIL_DATA = "GBQ_GRAPH_FAIL_DATA";
export const DELETE_GBQ_GRAPH_FAIL = "DELETE_GBQ_GRAPH_FAIL";
export const POST_GBQ_GRAPH_DATA = "POST_GBQ_GRAPH_DATA";
export const POST_GBQ_GRAPH_DATA_START = "POST_GBQ_GRAPH_DATA_START";
export const POST_GBQ_GRAPH_DATA_FAIL = "POST_GBQ_GRAPH_DATA_FAIL";
export const POST_GBQ_GRAPH_DATA_SUCCESS = "POST_GBQ_GRAPH_DATA_SUCCESS";
export const EDIT_GBQ_GRAPH_ROW_START = "EDIT_GBQ_GRAPH_ROW_START";

export const FAIL_EDIT_GBQ_GRAPH = "FAIL_EDIT_GBQ_GRAPH";
export const CURRENT_USER_EDIT_GBQ_GRAPH = "CURRENT_USER_EDIT_GBQ_GRAPH";
export const UPDATE_GBQ_GRAPH_DATA_START = "UPDATE_GBQ_GRAPH_DATA_START";
export const UPDATE_GBQ_GRAPH_DATA_FAIL = "UPDATE_GBQ_GRAPH_DATA_FAIL";
export const UPDATE_GBQ_GRAPH_DATA_SUCCESS = "UPDATE_GBQ_GRAPH_DATA_SUCCESS";
export const GBQ_GRAPH_LOADING = "GBQ_GRAPH_LOADING";
export const GBQ_GRAPH_POST_LOADING = "GBQ_GRAPH_POST_LOADING";
export const GBQ_GRAPH_UPDATE_LOADING = "GBQ_GRAPH_UPDATE_LOADING";

// GSQ GRAPH actionTypes

export const GSQ_GRAPH_GET_DATA = "GSQ_GRAPH_GET_DATA";
export const GSQ_GRAPH_SET_DATA = "GSQ_GRAPH_SET_DATA";
export const GSQ_GRAPH_FAIL_DATA = "GSQ_GRAPH_FAIL_DATA";
export const GSQ_GRAPH_LOADING = "GSQ_GRAPH_LOADING";

// Payment actionTypes

export const PAYMENT_GET_DATA = "PAYMENT_GET_DATA";
export const PAYMENT_SET_DATA = "PAYMENT_SET_DATA";
export const PAYMENT_FAIL_DATA = "PAYMENT_FAIL_DATA";
export const DELETE_PAYMENT_FAIL = "DELETE_PAYMENT_FAIL";
export const POST_PAYMENT_DATA = "POST_PAYMENT_DATA";
export const POST_PAYMENT_DATA_START = "POST_PAYMENT_DATA_START";
export const POST_PAYMENT_DATA_FAIL = "POST_PAYMENT_DATA_FAIL";
export const POST_PAYMENT_DATA_SUCCESS = "POST_PAYMENT_DATA_SUCCESS";
export const EDIT_PAYMENT_ROW_START = "EDIT_PAYMENT_ROW_START";

export const FAIL_EDIT_PAYMENT = "FAIL_EDIT_PAYMENT";
export const CURRENT_USER_EDIT_PAYMENT = "CURRENT_USER_EDIT_PAYMENT";
export const UPDATE_PAYMENT_DATA_START = "UPDATE_PAYMENT_DATA_START";
export const UPDATE_PAYMENT_DATA_FAIL = "UPDATE_PAYMENT_DATA_FAIL";
export const UPDATE_PAYMENT_DATA_SUCCESS = "UPDATE_PAYMENT_DATA_SUCCESS";
export const PAYMENT_LOADING = "PAYMENT_LOADING";
export const PAYMENT_POST_LOADING = "PAYMENT_POST_LOADING";
export const PAYMENT_UPDATE_LOADING = "PAYMENT_UPDATE_LOADING";

// Pending shipment actionTypes

export const PENDING_SHIPMENT_GET_DATA = "PENDING_SHIPMENT_GET_DATA";
export const PENDING_SHIPMENT_SET_DATA = "PENDING_SHIPMENT_SET_DATA";
export const PENDING_SHIPMENT_FAIL_DATA = "PENDING_SHIPMENT_FAIL_DATA";
export const DELETE_PENDING_SHIPMENT_FAIL = "DELETE_PENDING_SHIPMENT_FAIL";
export const POST_PENDING_SHIPMENT_DATA = "POST_PENDING_SHIPMENT_DATA";
export const POST_PENDING_SHIPMENT_DATA_START =
  "POST_PENDING_SHIPMENT_DATA_START";
export const POST_PENDING_SHIPMENT_DATA_FAIL =
  "POST_PENDING_SHIPMENT_DATA_FAIL";
export const POST_PENDING_SHIPMENT_DATA_SUCCESS =
  "POST_PENDING_SHIPMENT_DATA_SUCCESS";
export const EDIT_PENDING_SHIPMENT_ROW_START =
  "EDIT_PENDING_SHIPMENT_ROW_START";

export const FAIL_EDIT_PENDING_SHIPMENT = "FAIL_EDIT_PENDING_SHIPMENT";
export const CURRENT_USER_EDIT_PENDING_SHIPMENT =
  "CURRENT_USER_EDIT_PENDING_SHIPMENT";
export const UPDATE_PENDING_SHIPMENT_DATA_START =
  "UPDATE_PENDING_SHIPMENT_DATA_START";
export const UPDATE_PENDING_SHIPMENT_DATA_FAIL =
  "UPDATE_PENDING_SHIPMENT_DATA_FAIL";
export const UPDATE_PENDING_SHIPMENT_DATA_SUCCESS =
  "UPDATE_PENDING_SHIPMENT_DATA_SUCCESS";
export const PENDING_SHIPMENT_LOADING = "PENDING_SHIPMENT_LOADING";
export const PENDING_SHIPMENT_POST_LOADING = "PENDING_SHIPMENT_POST_LOADING";
export const PENDING_SHIPMENT_UPDATE_LOADING =
  "PENDING_SHIPMENT_UPDATE_LOADING";

// LME Fixation actionTypes

export const LME_FIXATION_GET_DATA = "LME_FIXATION_GET_DATA";
export const LME_FIXATION_SET_DATA = "LME_FIXATION_SET_DATA";
export const LME_FIXATION_FAIL_DATA = "LME_FIXATION_FAIL_DATA";
export const DELETE_LME_FIXATION_FAIL = "DELETE_LME_FIXATION_FAIL";
export const POST_LME_FIXATION_DATA = "POST_LME_FIXATION_DATA";
export const POST_LME_FIXATION_DATA_START = "POST_LME_FIXATION_DATA_START";
export const POST_LME_FIXATION_DATA_FAIL = "POST_LME_FIXATION_DATA_FAIL";
export const POST_LME_FIXATION_DATA_SUCCESS = "POST_LME_FIXATION_DATA_SUCCESS";
export const EDIT_LME_FIXATION_ROW_START = "EDIT_LME_FIXATION_ROW_START";

export const FAIL_EDIT_LME_FIXATION = "FAIL_EDIT_LME_FIXATION";
export const CURRENT_USER_EDIT_LME_FIXATION = "CURRENT_USER_EDIT_LME_FIXATION";
export const UPDATE_LME_FIXATION_DATA_START = "UPDATE_LME_FIXATION_DATA_START";
export const UPDATE_LME_FIXATION_DATA_FAIL = "UPDATE_LME_FIXATION_DATA_FAIL";
export const UPDATE_LME_FIXATION_DATA_SUCCESS =
  "UPDATE_LME_FIXATION_DATA_SUCCESS";
export const LME_FIXATION_LOADING = "LME_FIXATION_LOADING";
export const LME_FIXATION_POST_LOADING = "LME_FIXATION_POST_LOADING";
export const LME_FIXATION_UPDATE_LOADING = "LME_FIXATION_UPDATE_LOADING";

// Metric Ton actionTypes

export const METRIC_TON_GET_DATA = "METRIC_TON_GET_DATA";
export const METRIC_TON_SET_DATA = "METRIC_TON_SET_DATA";
export const METRIC_TON_FAIL_DATA = "METRIC_TON_FAIL_DATA";
export const DELETE_METRIC_TON_FAIL = "DELETE_METRIC_TON_FAIL";
export const POST_METRIC_TON_DATA = "POST_METRIC_TON_DATA";
export const POST_METRIC_TON_DATA_START = "POST_METRIC_TON_DATA_START";
export const POST_METRIC_TON_DATA_FAIL = "POST_METRIC_TON_DATA_FAIL";
export const POST_METRIC_TON_DATA_SUCCESS = "POST_METRIC_TON_DATA_SUCCESS";
export const EDIT_METRIC_TON_ROW_START = "EDIT_METRIC_TON_ROW_START";

export const FAIL_EDIT_METRIC_TON = "FAIL_EDIT_METRIC_TON";
export const CURRENT_USER_EDIT_METRIC_TON = "CURRENT_USER_EDIT_METRIC_TON";
export const UPDATE_METRIC_TON_DATA_START = "UPDATE_METRIC_TON_DATA_START";
export const UPDATE_METRIC_TON_DATA_FAIL = "UPDATE_METRIC_TON_DATA_FAIL";
export const UPDATE_METRIC_TON_DATA_SUCCESS = "UPDATE_METRIC_TON_DATA_SUCCESS";
export const METRIC_TON_LOADING = "METRIC_TON_LOADING";
export const METRIC_TON_POST_LOADING = "METRIC_TON_POST_LOADING";
export const METRIC_TON_UPDATE_LOADING = "METRIC_TON_UPDATE_LOADING";

//  Long Term Deposit actionTypes

export const LONG_TERM_GET_DATA = "LONG_TERM_GET_DATA";
export const LONG_TERM_SET_DATA = "LONG_TERM_SET_DATA";
export const LONG_TERM_FAIL_DATA = "LONG_TERM_FAIL_DATA";
export const DELETE_LONG_TERM_FAIL = "DELETE_LONG_TERM_FAIL";
export const POST_LONG_TERM_DATA = "POST_LONG_TERM_DATA";
export const POST_LONG_TERM_DATA_START = "POST_LONG_TERM_DATA_START";
export const POST_LONG_TERM_DATA_FAIL = "POST_LONG_TERM_DATA_FAIL";
export const POST_LONG_TERM_DATA_SUCCESS = "POST_LONG_TERM_DATA_SUCCESS";
export const EDIT_LONG_TERM_ROW_START = "EDIT_LONG_TERM_ROW_START";

export const FAIL_EDIT_LONG_TERM = "FAIL_EDIT_LONG_TERM";
export const CURRENT_USER_EDIT_LONG_TERM = "CURRENT_USER_EDIT_LONG_TERM";
export const UPDATE_LONG_TERM_DATA_START = "UPDATE_LONG_TERM_DATA_START";
export const UPDATE_LONG_TERM_DATA_FAIL = "UPDATE_LONG_TERM_DATA_FAIL";
export const UPDATE_LONG_TERM_DATA_SUCCESS = "UPDATE_LONG_TERM_DATA_SUCCESS";
export const LONG_TERM_LOADING = "LONG_TERM_LOADING";
export const LONG_TERM_POST_LOADING = "LONG_TERM_POST_LOADING";
export const LONG_TERM_UPDATE_LOADING = "LONG_TERM_UPDATE_LOADING";

// LME  Order history actionTypes

export const LME_ORDER_GET_DATA = "LME_ORDER_GET_DATA";
export const LME_ORDER_SET_DATA = "LME_ORDER_SET_DATA";
export const LME_ORDER_FAIL_DATA = "LME_ORDER_FAIL_DATA";
export const DELETE_LME_ORDER_FAIL = "DELETE_LME_ORDER_FAIL";
export const POST_LME_ORDER_DATA = "POST_LME_ORDER_DATA";
export const POST_LME_ORDER_DATA_START = "POST_LME_ORDER_DATA_START";
export const POST_LME_ORDER_DATA_FAIL = "POST_LME_ORDER_DATA_FAIL";
export const POST_LME_ORDER_DATA_SUCCESS = "POST_LME_ORDER_DATA_SUCCESS";
export const EDIT_LME_ORDER_ROW_START = "EDIT_LME_ORDER_ROW_START";

export const FAIL_EDIT_LME_ORDER = "FAIL_EDIT_LME_ORDER";
export const CURRENT_USER_EDIT_LME_ORDER = "CURRENT_USER_EDIT_LME_ORDER";
export const UPDATE_LME_ORDER_DATA_START = "UPDATE_LME_ORDER_DATA_START";
export const UPDATE_LME_ORDER_DATA_FAIL = "UPDATE_LME_ORDER_DATA_FAIL";
export const UPDATE_LME_ORDER_DATA_SUCCESS = "UPDATE_LME_ORDER_DATA_SUCCESS";
export const LME_ORDER_LOADING = "LME_ORDER_LOADING";
export const LME_ORDER_POST_LOADING = "LME_ORDER_POST_LOADING";
export const LME_ORDER_UPDATE_LOADING = "LME_ORDER_UPDATE_LOADING";

// Claims history actionTypes

export const CLAIMS_GET_DATA = "CLAIMS_GET_DATA";
export const CLAIMS_SET_DATA = "CLAIMS_SET_DATA";
export const CLAIMS_FAIL_DATA = "CLAIMS_FAIL_DATA";
export const DELETE_CLAIMS_FAIL = "DELETE_CLAIMS_FAIL";
export const POST_CLAIMS_DATA = "POST_CLAIMS_DATA";
export const POST_CLAIMS_DATA_START = "POST_CLAIMS_DATA_START";
export const POST_CLAIMS_DATA_FAIL = "POST_CLAIMS_DATA_FAIL";
export const POST_CLAIMS_DATA_SUCCESS = "POST_CLAIMS_DATA_SUCCESS";
export const EDIT_CLAIMS_ROW_START = "EDIT_CLAIMS_ROW_START";

export const FAIL_EDIT_CLAIMS = "FAIL_EDIT_CLAIMS";
export const CURRENT_USER_EDIT_CLAIMS = "CURRENT_USER_EDIT_CLAIMS";
export const UPDATE_CLAIMS_DATA_START = "UPDATE_CLAIMS_DATA_START";
export const UPDATE_CLAIMS_DATA_FAIL = "UPDATE_CLAIMS_DATA_FAIL";
export const UPDATE_CLAIMS_DATA_SUCCESS = "UPDATE_CLAIMS_DATA_SUCCESS";
export const CLAIMS_LOADING = "CLAIMS_LOADING";
export const CLAIMS_POST_LOADING = "CLAIMS_POST_LOADING";
export const CLAIMS_UPDATE_LOADING = "CLAIMS_UPDATE_LOADING";

// Invoice actionTypes

export const INVOICE_GET_DATA = "INVOICE_GET_DATA";
export const INVOICE_SET_DATA = "INVOICE_SET_DATA";
export const INVOICE_FAIL_DATA = "INVOICE_FAIL_DATA";
export const DELETE_INVOICE_FAIL = "DELETE_INVOICE_FAIL";
export const POST_INVOICE_DATA = "POST_INVOICE_DATA";
export const POST_INVOICE_DATA_START = "POST_INVOICE_DATA_START";
export const POST_INVOICE_DATA_FAIL = "POST_INVOICE_DATA_FAIL";
export const POST_INVOICE_DATA_SUCCESS = "POST_INVOICE_DATA_SUCCESS";
export const EDIT_INVOICE_ROW_START = "EDIT_INVOICE_ROW_START";

export const FAIL_EDIT_INVOICE = "FAIL_EDIT_INVOICE";
export const CURRENT_USER_EDIT_INVOICE = "CURRENT_USER_EDIT_INVOICE";
export const UPDATE_INVOICE_DATA_START = "UPDATE_INVOICE_DATA_START";
export const UPDATE_INVOICE_DATA_FAIL = "UPDATE_INVOICE_DATA_FAIL";
export const UPDATE_INVOICE_DATA_SUCCESS = "UPDATE_INVOICE_DATA_SUCCESS";
export const INVOICE_LOADING = "INVOICE_LOADING";
export const INVOICE_POST_LOADING = "INVOICE_POST_LOADING";
export const INVOICE_UPDATE_LOADING = "INVOICE_UPDATE_LOADING";

// Couriers actionTypes

export const COURIERS_GET_DATA = "COURIERS_GET_DATA";
export const COURIERS_SET_DATA = "COURIERS_SET_DATA";
export const COURIERS_FAIL_DATA = "COURIERS_FAIL_DATA";
export const DELETE_COURIERS_FAIL = "DELETE_COURIERS_FAIL";
export const POST_COURIERS_DATA = "POST_COURIERS_DATA";
export const POST_COURIERS_DATA_START = "POST_COURIERS_DATA_START";
export const POST_COURIERS_DATA_FAIL = "POST_COURIERS_DATA_FAIL";
export const POST_COURIERS_DATA_SUCCESS = "POST_COURIERS_DATA_SUCCESS";
export const EDIT_COURIERS_ROW_START = "EDIT_COURIERS_ROW_START";

export const FAIL_EDIT_COURIERS = "FAIL_EDIT_COURIERS";
export const CURRENT_USER_EDIT_COURIERS = "CURRENT_USER_EDIT_COURIERS";
export const UPDATE_COURIERS_DATA_START = "UPDATE_COURIERS_DATA_START";
export const UPDATE_COURIERS_DATA_FAIL = "UPDATE_COURIERS_DATA_FAIL";
export const UPDATE_COURIERS_DATA_SUCCESS = "UPDATE_COURIERS_DATA_SUCCESS";
export const COURIERS_LOADING = "COURIERS_LOADING";
export const COURIERS_POST_LOADING = "COURIERS_POST_LOADING";
export const COURIERS_UPDATE_LOADING = "COURIERS_UPDATE_LOADING";

// Users actionTypes

export const USERS_GET_DATA = "USERS_GET_DATA";
export const USERS_SET_DATA = "USERS_SET_DATA";
export const USERS_FAIL_DATA = "USERS_FAIL_DATA";
export const DELETE_USERS_FAIL = "DELETE_USERS_FAIL";
export const POST_USERS_DATA = "POST_USERS_DATA";
export const POST_USERS_DATA_START = "POST_USERS_DATA_START";
export const POST_USERS_DATA_FAIL = "POST_USERS_DATA_FAIL";
export const POST_USERS_DATA_SUCCESS = "POST_USERS_DATA_SUCCESS";
export const EDIT_USERS_ROW_START = "EDIT_USERS_ROW_START";

export const FAIL_EDIT_USERS = "FAIL_EDIT_USERS";
export const CURRENT_USER_EDIT_USERS = "CURRENT_USER_EDIT_USERS";
export const UPDATE_USERS_DATA_START = "UPDATE_USERS_DATA_START";
export const UPDATE_USERS_DATA_FAIL = "UPDATE_USERS_DATA_FAIL";
export const UPDATE_USERS_DATA_SUCCESS = "UPDATE_USERS_DATA_SUCCESS";
export const USERS_LOADING = "USERS_LOADING";
export const USERS_POST_LOADING = "USERS_POST_LOADING";
export const USERS_UPDATE_LOADING = "USERS_UPDATE_LOADING";

// Rights actionTypes

export const RIGHTS_GET_DATA = "RIGHTS_GET_DATA";
export const RIGHTS_SET_DATA = "RIGHTS_SET_DATA";
export const RIGHTS_FAIL_DATA = "RIGHTS_FAIL_DATA";
export const DELETE_RIGHTS_FAIL = "DELETE_RIGHTS_FAIL";
export const POST_RIGHTS_DATA = "POST_RIGHTS_DATA";
export const POST_RIGHTS_DATA_START = "POST_RIGHTS_DATA_START";
export const POST_RIGHTS_DATA_FAIL = "POST_RIGHTS_DATA_FAIL";
export const POST_RIGHTS_DATA_SUCCESS = "POST_RIGHTS_DATA_SUCCESS";
export const EDIT_RIGHTS_ROW_START = "EDIT_RIGHTS_ROW_START";

export const FAIL_EDIT_RIGHTS = "FAIL_EDIT_RIGHTS";
export const CURRENT_USER_EDIT_RIGHTS = "CURRENT_USER_EDIT_RIGHTS";
export const UPDATE_RIGHTS_DATA_START = "UPDATE_RIGHTS_DATA_START";
export const UPDATE_RIGHTS_DATA_FAIL = "UPDATE_RIGHTS_DATA_FAIL";
export const UPDATE_RIGHTS_DATA_SUCCESS = "UPDATE_RIGHTS_DATA_SUCCESS";
export const RIGHTS_LOADING = "RIGHTS_LOADING";
export const RIGHTS_POST_LOADING = "RIGHTS_POST_LOADING";
export const RIGHTS_UPDATE_LOADING = "RIGHTS_UPDATE_LOADING";

// long term payment actionTypes

export const LONG_TERM_PAYMENT_GET_DATA = "LONG_TERM_PAYMENT_GET_DATA";
export const LONG_TERM_PAYMENT_SET_DATA = "LONG_TERM_PAYMENT_SET_DATA";
export const LONG_TERM_PAYMENT_FAIL_DATA = "LONG_TERM_PAYMENT_FAIL_DATA";
export const DELETE_LONG_TERM_PAYMENT_FAIL = "DELETE_LONG_TERM_PAYMENT_FAIL";
export const POST_LONG_TERM_PAYMENT_DATA = "POST_LONG_TERM_PAYMENT_DATA";
export const POST_LONG_TERM_PAYMENT_DATA_START =
  "POST_LONG_TERM_PAYMENT_DATA_START";
export const POST_LONG_TERM_PAYMENT_DATA_FAIL =
  "POST_LONG_TERM_PAYMENT_DATA_FAIL";
export const POST_LONG_TERM_PAYMENT_DATA_SUCCESS =
  "POST_LONG_TERM_PAYMENT_DATA_SUCCESS";
export const EDIT_LONG_TERM_PAYMENT_ROW_START =
  "EDIT_LONG_TERM_PAYMENT_ROW_START";

export const FAIL_EDIT_LONG_TERM_PAYMENT = "FAIL_EDIT_LONG_TERM_PAYMENT";
export const CURRENT_USER_EDIT_LONG_TERM_PAYMENT =
  "CURRENT_USER_EDIT_LONG_TERM_PAYMENT";
export const UPDATE_LONG_TERM_PAYMENT_DATA_START =
  "UPDATE_LONG_TERM_PAYMENT_DATA_START";
export const UPDATE_LONG_TERM_PAYMENT_DATA_FAIL =
  "UPDATE_LONG_TERM_PAYMENT_DATA_FAIL";
export const UPDATE_LONG_TERM_PAYMENT_DATA_SUCCESS =
  "UPDATE_LONG_TERM_PAYMENT_DATA_SUCCESS";
export const LONG_TERM_PAYMENT_LOADING = "LONG_TERM_PAYMENT_LOADING";
export const LONG_TERM_PAYMENT_POST_LOADING = "LONG_TERM_PAYMENT_POST_LOADING";
export const LONG_TERM_PAYMENT_UPDATE_LOADING =
  "LONG_TERM_PAYMENT_UPDATE_LOADING";

// Couriers actionTypes

export const COM_DESCRIPTION_GET_DATA = "COM_DESCRIPTION_GET_DATA";
export const COM_DESCRIPTION_SET_DATA = "COM_DESCRIPTION_SET_DATA";
export const COM_DESCRIPTION_FAIL_DATA = "COM_DESCRIPTION_FAIL_DATA";
export const DELETE_COM_DESCRIPTION_FAIL = "DELETE_COM_DESCRIPTION_FAIL";
export const POST_COM_DESCRIPTION_DATA = "POST_COM_DESCRIPTION_DATA";
export const POST_COM_DESCRIPTION_DATA_START =
  "POST_COM_DESCRIPTION_DATA_START";
export const POST_COM_DESCRIPTION_DATA_FAIL = "POST_COM_DESCRIPTION_DATA_FAIL";
export const POST_COM_DESCRIPTION_DATA_SUCCESS =
  "POST_COM_DESCRIPTION_DATA_SUCCESS";
export const EDIT_COM_DESCRIPTION_ROW_START = "EDIT_COM_DESCRIPTION_ROW_START";

export const FAIL_EDIT_COM_DESCRIPTION = "FAIL_EDIT_COM_DESCRIPTION";
export const CURRENT_USER_EDIT_COM_DESCRIPTION =
  "CURRENT_USER_EDIT_COM_DESCRIPTION";
export const UPDATE_COM_DESCRIPTION_DATA_START =
  "UPDATE_COM_DESCRIPTION_DATA_START";
export const UPDATE_COM_DESCRIPTION_DATA_FAIL =
  "UPDATE_COM_DESCRIPTION_DATA_FAIL";
export const UPDATE_COM_DESCRIPTION_DATA_SUCCESS =
  "UPDATE_COM_DESCRIPTION_DATA_SUCCESS";
export const COM_DESCRIPTION_LOADING = "COM_DESCRIPTION_LOADING";
export const COM_DESCRIPTION_POST_LOADING = "COM_DESCRIPTION_POST_LOADING";
export const COM_DESCRIPTION_UPDATE_LOADING = "COM_DESCRIPTION_UPDATE_LOADING";
